name: env_neural_avh
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11.4
  - pip=23.3.1
  - pytorch=2.1.0
  - torchaudio==2.1.0
  - torchvision==0.16.0
  - pytorch-cuda=12.1
  - colorama=0.4.6
  - ipython=8.21.0
  - lightning=2.2.1
  - numpy=1.26.4
  - tqdm=4.66.2
  - pip:
    - audiocraft==1.2.0
    - gitpython==3.1.42
    - huggingface-hub==0.20.3
    - librosa==0.10.1
    - matplotlib==3.8.3
    - numba==0.59.0
    - pretty-midi==0.2.10
    - python-dotenv==1.0.1
    - scipy==1.12.0
    - soundfile==0.12.1
    - tensorboard==2.16.2
    - tokenizers==0.15.2
