name: env_neural_avh
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11.4
  - pip
  - pytorch
  - torchaudio
  - torchvision
  - pytorch-cuda=11.8
  - colorama
  - ipython
  - lightning
  - numpy
  - tqdm
  - pip:
    - audiocraft
    - gitpython
    - huggingface-hub
    - librosa
    - matplotlib
    - numba
    - pretty-midi
    - python-dotenv
    - scipy
    - soundfile
    - tensorboard
    - tokenizers
